@VueExample.Server_HostAddress = http://localhost:5142

GET {{VueExample.Server_HostAddress}}/weatherforecast/
Accept: application/json

# POST {{VueExample.Server_HostAddress}}/api/authenticate/
# Accept: application/json

# GET {{VueExample.Server_HostAddress}}/api/quizes/1
# Accept: application/json

###
